{
  imports = [
    # Enable &/ Configure Programs
    ./bash.nix
    ./gtk-qt.nix
    ./hyprland.nix
    ./kdenlive.nix
    ./kitty.nix
    ./neofetch.nix
    ./packages.nix
    ./rofi.nix
    ./starship.nix
    ./waybar.nix
    ./wlogout.nix
    ./swappy.nix
    ./swaync.nix
    ./zoxide.nix
    ./obs-studio.nix
    ./gimp.nix
    ./git.nix
    ./brave.nix
    ./vesktop.nix
    ./eza.nix
    # Place Home Files Like Pictures
    ./files.nix
    ./yazi.nix
    ./fish.nix
    ./zathura.nix
    ./firefox.nix
    ./spotify.nix
    ./hyprlock.nix
    ./btop.nix
    ./cava.nix
    ./bat.nix
    ./nixvim
    ./fastfetch.nix
    ./vscode.nix
    ./direnv.nix
    ./zsh.nix
  ];
}
